/// S-parameter representation and Touchstone export for 2-port networks.
use serde::{Deserialize, Serialize};

/// 2-port S-parameter data across frequency.
/// Each S-parameter entry is a (magnitude, phase_degrees) tuple.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SParameter {
    /// Frequency points in GHz.
    pub freq_ghz: Vec<f64>,
    /// S11 (input reflection): (magnitude, phase_deg) per frequency.
    pub s11: Vec<(f64, f64)>,
    /// S21 (forward transmission): (magnitude, phase_deg) per frequency.
    pub s21: Vec<(f64, f64)>,
    /// S12 (reverse transmission): (magnitude, phase_deg) per frequency.
    pub s12: Vec<(f64, f64)>,
    /// S22 (output reflection): (magnitude, phase_deg) per frequency.
    pub s22: Vec<(f64, f64)>,
}

/// Summary metrics extracted from S-parameter data.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SParamMetrics {
    /// Worst-case insertion loss (S21 magnitude in dB).
    pub insertion_loss_db: f64,
    /// Worst-case return loss (S11 magnitude in dB).
    pub return_loss_db: f64,
    /// 3dB bandwidth in GHz.
    pub bandwidth_3db_ghz: f64,
}

impl SParameter {
    /// Compute summary metrics from the S-parameter data.
    pub fn metrics(&self) -> SParamMetrics {
        let insertion_loss_db = self
            .s21
            .iter()
            .map(|(mag, _)| 20.0 * mag.log10())
            .fold(f64::INFINITY, f64::min);

        let return_loss_db = self
            .s11
            .iter()
            .map(|(mag, _)| -20.0 * mag.log10())
            .fold(f64::INFINITY, f64::min);

        // Find 3dB bandwidth: first frequency where |S21| drops 3dB from DC.
        let s21_db_0 = if let Some((mag, _)) = self.s21.first() {
            20.0 * mag.log10()
        } else {
            0.0
        };

        let bandwidth_3db_ghz = self
            .freq_ghz
            .iter()
            .zip(self.s21.iter())
            .find(|(_, (mag, _))| 20.0 * mag.log10() < s21_db_0 - 3.0)
            .map(|(f, _)| *f)
            .unwrap_or(*self.freq_ghz.last().unwrap_or(&0.0));

        SParamMetrics {
            insertion_loss_db,
            return_loss_db,
            bandwidth_3db_ghz,
        }
    }
}

/// Export S-parameter data in Touchstone .s2p format (Version 1).
///
/// Format: `# GHz S MA R 50` header followed by frequency-ordered rows of
/// `freq S11_mag S11_phase S21_mag S21_phase S12_mag S12_phase S22_mag S22_phase`.
pub fn export_touchstone(sparam: &SParameter) -> String {
    let mut out = String::with_capacity(sparam.freq_ghz.len() * 120);
    out.push_str("! Touchstone .s2p generated by kami-si\n");
    out.push_str("# GHz S MA R 50\n");

    for (i, freq) in sparam.freq_ghz.iter().enumerate() {
        let (s11m, s11p) = sparam.s11[i];
        let (s21m, s21p) = sparam.s21[i];
        let (s12m, s12p) = sparam.s12[i];
        let (s22m, s22p) = sparam.s22[i];
        out.push_str(&format!(
            "{:.6e}  {:.6e} {:.3}  {:.6e} {:.3}  {:.6e} {:.3}  {:.6e} {:.3}\n",
            freq, s11m, s11p, s21m, s21p, s12m, s12p, s22m, s22p,
        ));
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_sparam() -> SParameter {
        SParameter {
            freq_ghz: vec![0.1, 1.0, 5.0, 10.0, 20.0],
            s11: vec![
                (0.05, -10.0),
                (0.08, -20.0),
                (0.15, -45.0),
                (0.25, -80.0),
                (0.40, -120.0),
            ],
            s21: vec![
                (0.98, -5.0),
                (0.95, -15.0),
                (0.80, -40.0),
                (0.55, -90.0),
                (0.30, -150.0),
            ],
            s12: vec![
                (0.01, 170.0),
                (0.02, 160.0),
                (0.03, 140.0),
                (0.04, 100.0),
                (0.05, 60.0),
            ],
            s22: vec![
                (0.04, -8.0),
                (0.06, -18.0),
                (0.12, -40.0),
                (0.20, -70.0),
                (0.35, -110.0),
            ],
        }
    }

    #[test]
    fn touchstone_export_has_header() {
        let sp = sample_sparam();
        let ts = export_touchstone(&sp);
        assert!(ts.contains("# GHz S MA R 50"), "Missing Touchstone header");
        let data_lines: Vec<&str> = ts
            .lines()
            .filter(|l| !l.starts_with('!') && !l.starts_with('#'))
            .collect();
        assert_eq!(
            data_lines.len(),
            5,
            "Should have one line per frequency point"
        );
    }

    #[test]
    fn metrics_insertion_loss_negative_db() {
        let sp = sample_sparam();
        let m = sp.metrics();
        assert!(
            m.insertion_loss_db < 0.0,
            "Insertion loss should be negative dB"
        );
    }
}
