//! `VectorizedEeReachEnv` — an end-effector **Cartesian** reach task, the direct
//! precursor to the Franka pick-and-place reference (R1.5).
//!
//! Where `VectorizedReachEnv` rewards reaching a joint-space goal, this rewards
//! placing the end-effector **link** at a 3-D world target — the actual
//! manipulation signal Isaac Lab's reach tasks use. It wraps the same
//! `kami_genesis::ArticulationBatch`, observing the end-effector pose via
//! `get_world_poses`.
//!
//! Reachable goals are generated by sampling a random joint configuration per
//! env and running forward kinematics (set that pose, read the EE position),
//! then resetting the arm — so every goal is reachable by construction, and the
//! generating configuration is exposed as a reference IK solution for testing.
//!
//! Layout (env-major flat):
//!   - action: `[num_envs, n_dof]` joint **position targets**
//!   - observation: `[num_envs, 2*n_dof + 6]` = `[q, q̇, ee_pos(3), goal − ee_pos(3)]`
//!   - reward: `−‖ee_pos − goal‖² − w·‖action‖²`
//!   - terminated: `‖ee_pos − goal‖ < goal_tol` (metres)

use crate::reach_env::{Lcg, ReachCfg};
use crate::traits::{StepResult, VecRLEnv};
use kami_articulated::parse_urdf;
use kami_genesis::ArticulationBatch;
use kami_sensor_sim::{ContactSensor, Primitive, Scene};

/// Vectorized end-effector Cartesian reach env over `num_envs` copies of one arm.
pub struct VectorizedEeReachEnv {
    batch: ArticulationBatch,
    pub num_envs: usize,
    ndof: usize,
    ee_link: String,
    cfg: ReachCfg,
    /// Per-env Cartesian goal `[num_envs * 3]` (world x,y,z).
    goals: Vec<f32>,
    /// The joint configuration that generated each goal `[num_envs * n_dof]` —
    /// a valid reference IK solution (goals are reachable by construction).
    ref_q: Vec<f32>,
    steps: Vec<u32>,
    rngs: Vec<Lcg>,
    /// Independent RNG for action-noise DR (kept off the goal-sampling stream).
    noise_rng: Lcg,
    /// In-the-loop touch sensor (collision sphere = `cfg.contact_radius`), used
    /// only when `cfg.contact_radius > 0`.
    contact: ContactSensor,
}

impl VectorizedEeReachEnv {
    /// Build `num_envs` arms from `urdf_text`; `ee_link` is the end-effector link
    /// whose world position is the reach target. `cfg.goal_tol` is in metres.
    pub fn new(
        num_envs: usize,
        urdf_text: &str,
        ee_link: &str,
        cfg: ReachCfg,
    ) -> Result<Self, String> {
        if num_envs == 0 {
            return Err("num_envs must be > 0".to_string());
        }
        let sys = parse_urdf(urdf_text).map_err(|e| format!("urdf parse: {e:?}"))?;
        let gravity = glam::Vec3::new(0.0, 0.0, cfg.gravity_z);
        let batch = ArticulationBatch::from_urdf(&sys, gravity, cfg.dt, num_envs);
        let ndof = batch.num_dof();
        if ndof == 0 {
            return Err("articulation has no actuated DOF".to_string());
        }
        // Validate the EE link exists by probing a pose query.
        if batch.get_world_poses(ee_link).is_none() {
            return Err(format!("end-effector link '{ee_link}' not found"));
        }
        let rngs = (0..num_envs).map(|i| Lcg::new(i as u64)).collect();
        let contact = ContactSensor::new(
            "ee_touch",
            "/World/ee/touch",
            ee_link,
            cfg.contact_radius.max(0.0),
        );
        Ok(VectorizedEeReachEnv {
            batch,
            num_envs,
            ndof,
            ee_link: ee_link.to_string(),
            cfg,
            goals: vec![0.0; num_envs * 3],
            ref_q: vec![0.0; num_envs * ndof],
            steps: vec![0; num_envs],
            rngs,
            noise_rng: Lcg::new(0x9E37_79B9),
            contact,
        })
    }

    pub fn observation_dim_per_env(&self) -> usize {
        2 * self.ndof + 6 + if self.cfg.observe_contact { 1 } else { 0 }
    }

    /// Whether the end-effector of env `e` is in contact with its goal region
    /// (via the in-the-loop `ContactSensor`). Always false if `contact_radius` is 0.
    fn ee_in_contact(&self, ee: glam::Vec3, e: usize) -> bool {
        if self.cfg.contact_radius <= 0.0 {
            return false;
        }
        let mut scene = Scene::new();
        scene.add(Primitive::Sphere {
            center: glam::Vec3::new(
                self.goals[e * 3],
                self.goals[e * 3 + 1],
                self.goals[e * 3 + 2],
            ),
            radius: 0.0,
        });
        self.contact.sample(ee, &scene, 0.0).in_contact
    }

    pub fn action_dim_per_env(&self) -> usize {
        self.ndof
    }

    /// Per-env Cartesian goals `[num_envs * 3]` (world x,y,z).
    pub fn goals(&self) -> &[f32] {
        &self.goals
    }

    /// The reference joint solution that places each EE at its goal, `[num_envs *
    /// n_dof]`. Goals are sampled in joint space then mapped through FK, so this
    /// is a guaranteed-reachable IK solution (used by tests / as a demo policy).
    pub fn reference_joint_solution(&self) -> &[f32] {
        &self.ref_q
    }

    /// Override the per-env Cartesian goals with user-specified world targets
    /// (`[num_envs, 3]`). Unlike the FK-sampled reset goals, these need not be
    /// pre-solved — pair with [`solve_ik_to_goals`] for operational-space
    /// control. Invalidates `reference_joint_solution` (no longer the IK soln).
    pub fn set_cartesian_goals(&mut self, targets: &[f32]) {
        assert_eq!(targets.len(), self.num_envs * 3, "goal shape [num_envs, 3]");
        self.goals.copy_from_slice(targets);
    }

    /// Solve per-env inverse kinematics for the current Cartesian goals and
    /// return the `[num_envs, n_dof]` joint targets — Isaac's
    /// `compute_inverse_kinematics`. Feed straight to `step_all` for
    /// operational-space (Cartesian) goal reaching.
    pub fn solve_ik_to_goals(&self, iters: usize, lambda: f32) -> Vec<f32> {
        self.batch
            .solve_ik_point(
                &self.ee_link,
                self.cfg.tool_offset,
                &self.goals,
                iters,
                lambda,
            )
            .expect("ee_link validated in new()")
    }

    /// Per-env world position of the controlled tool point — the EE link frame
    /// origin shifted by `cfg.tool_offset` (rotated into the world). With a zero
    /// offset this is just the link origin.
    fn tool_world(&self) -> Vec<glam::Vec3> {
        let (pos, quat) = self.batch.get_world_poses(&self.ee_link).expect("ee link");
        let off = glam::Vec3::from(self.cfg.tool_offset);
        (0..self.num_envs)
            .map(|e| {
                let q = glam::Quat::from_xyzw(quat[e][1], quat[e][2], quat[e][3], quat[e][0]);
                glam::Vec3::from(pos[e]) + q * off
            })
            .collect()
    }

    /// Reset: sample a reachable per-env Cartesian goal (random joint config →
    /// tool-point FK), zero the arm, and return the initial observation.
    pub fn reset_all(&mut self, base_seed: Option<u64>) -> Vec<f32> {
        // 1. sample a reference joint config per env.
        if let Some(s) = base_seed {
            self.noise_rng = Lcg::new(s ^ 0xA5A5_1234);
        }
        let (g, m) = (self.cfg.gravity_dr, self.cfg.mass_dr);
        if g.is_some() || m.is_some() {
            self.batch.randomize_physics(
                base_seed.unwrap_or(0) ^ 0xD12,
                g.unwrap_or((1.0, 1.0)),
                m.unwrap_or((1.0, 1.0)),
            );
        } else {
            self.batch.clear_physics_randomization();
        }
        for e in 0..self.num_envs {
            if let Some(s) = base_seed {
                self.rngs[e] = Lcg::new(s.wrapping_add(e as u64));
            }
            for d in 0..self.ndof {
                self.ref_q[e * self.ndof + d] = self.rngs[e].next_signed() * self.cfg.goal_range;
            }
            self.steps[e] = 0;
        }
        // 2. FK: place the arm at the reference config, read the tool world pos.
        self.batch.set_joint_positions(&self.ref_q);
        self.batch
            .set_joint_velocities(&vec![0.0; self.num_envs * self.ndof]);
        let tool = self.tool_world();
        for e in 0..self.num_envs {
            self.goals[e * 3] = tool[e].x;
            self.goals[e * 3 + 1] = tool[e].y;
            self.goals[e * 3 + 2] = tool[e].z;
        }
        // 3. reset the arm to the zero pose for the episode start.
        self.batch.reset();
        self.observations_flat()
    }

    /// One control tick: `actions` are `[num_envs, n_dof]` joint position
    /// targets; drive the computed-torque actuator `decimation` substeps and
    /// return per-env `StepResult` scored on EE-to-goal Cartesian distance.
    pub fn step_all(&mut self, actions: &[f32]) -> Vec<StepResult> {
        assert_eq!(actions.len(), self.num_envs * self.ndof, "action shape");
        // Action-noise domain randomisation (reproducible, per-env uniform).
        let noised;
        let actions: &[f32] = if self.cfg.action_noise_std > 0.0 {
            let std = self.cfg.action_noise_std;
            noised = actions
                .iter()
                .map(|a| a + self.noise_rng.next_signed() * std)
                .collect::<Vec<f32>>();
            &noised
        } else {
            actions
        };
        self.batch
            .set_joint_position_targets(actions, self.cfg.kp, self.cfg.kd);
        self.batch
            .set_computed_torque_control(self.cfg.computed_torque);
        for _ in 0..self.cfg.decimation {
            self.batch.step();
        }

        let ee = self.tool_world();
        let mut obs_all = self.observations_flat();
        if self.cfg.obs_noise_std > 0.0 {
            let std = self.cfg.obs_noise_std;
            for v in obs_all.iter_mut() {
                *v += self.noise_rng.next_signed() * std;
            }
        }
        let od = self.observation_dim_per_env();
        let mut out = Vec::with_capacity(self.num_envs);
        for e in 0..self.num_envs {
            self.steps[e] += 1;
            let dx = ee[e].x - self.goals[e * 3];
            let dy = ee[e].y - self.goals[e * 3 + 1];
            let dz = ee[e].z - self.goals[e * 3 + 2];
            let sq = dx * dx + dy * dy + dz * dz;
            let act_sq: f32 = (0..self.ndof)
                .map(|d| actions[e * self.ndof + d].powi(2))
                .sum();
            // Touch bonus: reward contact with the goal region (sensor-in-loop).
            let bonus = if self.ee_in_contact(ee[e], e) {
                self.cfg.contact_bonus
            } else {
                0.0
            };
            out.push(StepResult {
                observation: obs_all[e * od..(e + 1) * od].to_vec(),
                reward: -sq - self.cfg.action_penalty * act_sq + bonus,
                terminated: sq.sqrt() < self.cfg.goal_tol,
                truncated: self.steps[e] >= self.cfg.max_steps,
            });
        }
        out
    }

    /// Observations env-major: `[q, q̇, ee_pos(3), goal − ee_pos(3)]` per env.
    pub fn observations_flat(&self) -> Vec<f32> {
        let q = self.batch.get_joint_positions();
        let qd = self.batch.get_joint_velocities();
        let ee = self.tool_world();
        let mut out = Vec::with_capacity(self.num_envs * self.observation_dim_per_env());
        for e in 0..self.num_envs {
            let base = e * self.ndof;
            out.extend_from_slice(&q[base..base + self.ndof]);
            out.extend_from_slice(&qd[base..base + self.ndof]);
            let p = ee[e];
            out.extend_from_slice(&[p.x, p.y, p.z]);
            out.push(self.goals[e * 3] - p.x);
            out.push(self.goals[e * 3 + 1] - p.y);
            out.push(self.goals[e * 3 + 2] - p.z);
            // Optional touch flag (0/1) as the final observation term.
            if self.cfg.observe_contact {
                out.push(if self.ee_in_contact(p, e) { 1.0 } else { 0.0 });
            }
        }
        out
    }
}

impl VecRLEnv for VectorizedEeReachEnv {
    fn num_envs(&self) -> usize {
        self.num_envs
    }
    fn observation_dim_per_env(&self) -> usize {
        Self::observation_dim_per_env(self)
    }
    fn action_dim_per_env(&self) -> usize {
        Self::action_dim_per_env(self)
    }
    fn reset_all(&mut self, base_seed: Option<u64>) -> Vec<f32> {
        Self::reset_all(self, base_seed)
    }
    fn step_all(&mut self, actions: &[f32]) -> Vec<StepResult> {
        Self::step_all(self, actions)
    }
    fn observations_flat(&self) -> Vec<f32> {
        Self::observations_flat(self)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const ARM2_URDF: &str = r#"<robot name="arm2">
<link name="base"><inertial><mass value="1"/><inertia ixx="0.01" iyy="0.01" izz="0.01" ixy="0" ixz="0" iyz="0"/></inertial></link>
<joint name="shoulder" type="revolute"><parent link="base"/><child link="upper"/><origin xyz="0 0 0"/><axis xyz="0 1 0"/><limit lower="-3.14" upper="3.14" effort="80" velocity="10"/><dynamics damping="0"/></joint>
<link name="upper"><inertial><origin xyz="0 0 -0.5"/><mass value="1"/><inertia ixx="0.02" iyy="0.02" izz="0.001" ixy="0" ixz="0" iyz="0"/></inertial></link>
<joint name="elbow" type="revolute"><parent link="upper"/><child link="fore"/><origin xyz="0 0 -1"/><axis xyz="0 1 0"/><limit lower="-3.14" upper="3.14" effort="80" velocity="10"/><dynamics damping="0"/></joint>
<link name="fore"><inertial><origin xyz="0 0 -0.5"/><mass value="1"/><inertia ixx="0.02" iyy="0.02" izz="0.001" ixy="0" ixz="0" iyz="0"/></inertial></link>
</robot>"#;

    fn env(num_envs: usize) -> VectorizedEeReachEnv {
        VectorizedEeReachEnv::new(num_envs, ARM2_URDF, "fore", ReachCfg::default()).unwrap()
    }

    #[test]
    fn shapes_and_unknown_ee_link_rejected() {
        let mut e = env(4);
        assert_eq!(e.action_dim_per_env(), 2);
        assert_eq!(e.observation_dim_per_env(), 2 * 2 + 6);
        let obs = e.reset_all(Some(0));
        assert_eq!(obs.len(), 4 * (2 * 2 + 6));
        assert!(obs.iter().all(|v| v.is_finite()));
        // Unknown EE link is a constructor error.
        assert!(VectorizedEeReachEnv::new(2, ARM2_URDF, "nope", ReachCfg::default()).is_err());
    }

    #[test]
    fn goals_are_reachable_and_seed_deterministic() {
        let mut a = env(3);
        let mut b = env(3);
        let oa = a.reset_all(Some(11));
        let ob = b.reset_all(Some(11));
        assert_eq!(oa, ob, "same seed → identical reset");
        // Goal must be within the arm's reach (total link length 2.0 from base).
        for e in 0..a.num_envs {
            let g = &a.goals()[e * 3..e * 3 + 3];
            let r = (g[0] * g[0] + g[1] * g[1] + g[2] * g[2]).sqrt();
            assert!(r <= 2.0 + 1e-3, "goal {r} outside reach");
        }
    }

    #[test]
    fn touch_reach_adds_contact_obs_and_bonus_on_arrival() {
        // Sensor-in-the-loop: contact observation grows obs by 1, and reaching
        // the goal trips the touch flag + adds the reward bonus.
        let cfg = ReachCfg {
            contact_radius: 0.08,
            contact_bonus: 10.0,
            observe_contact: true,
            ..ReachCfg::default()
        };
        let mut e = VectorizedEeReachEnv::new(2, ARM2_URDF, "fore", cfg).unwrap();
        // obs gains the contact flag.
        assert_eq!(e.observation_dim_per_env(), 2 * 2 + 6 + 1);
        e.reset_all(Some(4));
        let od = e.observation_dim_per_env();

        // Before driving: EE away from goal → contact flag 0, no bonus.
        let first = e.step_all(&e.reference_joint_solution().to_vec());
        assert!(first.iter().all(|s| s.observation.len() == od));
        let touch0: f32 = first[0].observation[od - 1];
        assert_eq!(touch0, 0.0, "should not be touching at start");

        // Drive to the goal; the touch flag flips to 1 and the bonus shows up
        // (terminal reward must exceed the no-bonus distance reward of ~0).
        let cmd = e.reference_joint_solution().to_vec();
        let mut last = e.step_all(&cmd);
        for _ in 0..299 {
            last = e.step_all(&cmd);
        }
        for s in &last {
            assert_eq!(s.observation[od - 1], 1.0, "touch flag not set at goal");
            assert!(
                s.reward > 5.0,
                "contact bonus not applied: reward {}",
                s.reward
            );
            assert!(s.terminated);
        }
    }

    #[test]
    fn tool_offset_reach_controls_the_tip_via_ik() {
        // With a tool offset down the fore link, the controlled point is the tip
        // (needs both joints). FK-sampled goals + IK must still reach it, and the
        // observation's ee_pos is the tool point (not the link origin).
        let cfg = ReachCfg {
            tool_offset: [0.0, 0.0, -0.5],
            ..ReachCfg::default()
        };
        let mut e = VectorizedEeReachEnv::new(2, ARM2_URDF, "fore", cfg).unwrap();
        let obs = e.reset_all(Some(3));
        let od = e.observation_dim_per_env();
        let ndof = e.action_dim_per_env();
        // ee_pos in the observation equals the goal at reset only if the arm were
        // at the sampling pose; here it's the zero pose, so just sanity-check shape.
        assert_eq!(obs.len(), e.num_envs * od);

        // IK to the tool-point goals, drive, and confirm arrival (tool reached).
        let cmd = e.solve_ik_to_goals(300, 0.01);
        let mut last = e.step_all(&cmd);
        for _ in 0..299 {
            last = e.step_all(&cmd);
        }
        assert!(
            last.iter().all(|s| s.terminated),
            "tool-point IK did not reach goal: {last:?}"
        );
        // The reported ee_pos (obs index 2*ndof..) is the tool point: it equals
        // the goal within tolerance now that we've arrived.
        let fin = e.observations_flat();
        for env in 0..e.num_envs {
            let b = env * od + 2 * ndof;
            let dx = fin[b] - e.goals()[env * 3];
            let dz = fin[b + 2] - e.goals()[env * 3 + 2];
            assert!((dx * dx + dz * dz).sqrt() < 0.05, "tool obs not at goal");
        }
    }

    #[test]
    fn operational_space_control_reaches_user_cartesian_goal_via_ik() {
        // Specify an *arbitrary* reachable Cartesian goal (not FK-sampled),
        // solve IK for it, drive there — true operational-space control.
        let mut e = VectorizedEeReachEnv::new(2, ARM2_URDF, "fore", ReachCfg::default()).unwrap();
        // Derive a reachable Cartesian goal from FK of a known config (the env
        // doesn't see the config — IK must recover it). reset_all leaves the
        // FK-sampled goals in place; we overwrite them with this Cartesian one.
        e.reset_all(Some(0));
        let goal = {
            // reference_joint_solution gives a reachable EE pose; reuse one env's
            // sampled goal as a guaranteed-reachable Cartesian target for all.
            let g = e.goals();
            [g[0], g[1], g[2], g[0], g[1], g[2]]
        };
        e.set_cartesian_goals(&goal);

        let cmd = e.solve_ik_to_goals(200, 0.01);
        let mut last = e.step_all(&cmd);
        for _ in 0..299 {
            last = e.step_all(&cmd);
        }
        assert!(
            last.iter().all(|s| s.terminated),
            "IK control did not reach goal: {last:?}"
        );
    }

    #[test]
    fn action_noise_dr_is_reproducible_and_perturbs_the_ee_trajectory() {
        let run = |std: f32| -> Vec<f32> {
            let cfg = ReachCfg {
                action_noise_std: std,
                ..ReachCfg::default()
            };
            let mut e = VectorizedEeReachEnv::new(2, ARM2_URDF, "fore", cfg).unwrap();
            e.reset_all(Some(8));
            let cmd = vec![0.3_f32; e.num_envs * e.action_dim_per_env()];
            for _ in 0..50 {
                e.step_all(&cmd);
            }
            e.observations_flat()
        };
        let a = run(0.2);
        let b = run(0.2);
        assert_eq!(a, b, "EE action-noise DR not reproducible");
        assert_ne!(
            a,
            run(0.0),
            "action noise had no effect on the EE trajectory"
        );
        assert!(a.iter().all(|v| v.is_finite()));
    }

    #[test]
    fn reference_policy_drives_ee_to_cartesian_goal() {
        // Commanding the reference joint solution must place every EE at its
        // 3-D goal (reward → ~0) and terminate, validating the FK/observation/
        // reward loop end-to-end.
        let mut e = env(4);
        e.reset_all(Some(2));
        let cmd = e.reference_joint_solution().to_vec();

        let first = e.step_all(&cmd);
        let r0: f32 = first.iter().map(|s| s.reward).sum();
        let mut last = first;
        for _ in 0..299 {
            last = e.step_all(&cmd);
        }
        let r1: f32 = last.iter().map(|s| s.reward).sum();
        assert!(r1 > r0, "reward did not improve: {r0} -> {r1}");
        assert!(
            last.iter().all(|s| s.terminated),
            "EE did not reach goal: {last:?}"
        );
    }
}
