//! process — the robot operation sequence per construction step.
//!
//! Loads `process.json` (generated by `process_gen.py`): each construction step
//! is a chain of robot operations (procure 調達 → deliver 搬入 → stage 搬送 →
//! build 建方/据付/敷設/打設 → fasten 締結/溶接 → inspect 検査). The tatekata
//! viewer plays these phases inside each step's window so the build is shown as
//! an executable robotics procedure, not just a geometry reveal.

use serde::Deserialize;

pub const PROCESS_JSON: &str =
    include_str!("../../../../70-tools/e7m-sim/scenes/giemon-factory-r0/process.json");

#[derive(Clone, Deserialize)]
pub struct Op {
    pub step: String,
    pub seq: u32,
    pub action: String,
    pub label: String,
    pub robot: String,
    pub from: String,
    pub to: String,
    pub dur_min: f32,
    pub process: String,
}

#[derive(Deserialize)]
pub struct Process {
    pub of: String,
    pub ops: Vec<Op>,
}

/// An op placed on the step's normalized timeline `[f0, f1)`.
#[derive(Clone)]
pub struct PhaseOp {
    pub op: Op,
    pub f0: f32,
    pub f1: f32,
}

/// Per-step playback plan: the ops with normalized time spans, plus the
/// `[build_start, build_end]` window during which geometry actually grows
/// (i.e. the 据付/締結 ops — after 調達/搬入/搬送, before 検査).
#[derive(Clone)]
pub struct StepPlan {
    pub ops: Vec<PhaseOp>,
    pub build_start: f32,
    pub build_end: f32,
}

fn is_build(action: &str) -> bool {
    !matches!(action, "procure" | "deliver" | "stage" | "inspect")
}

fn is_logistics(action: &str) -> bool {
    matches!(action, "deliver" | "stage")
}

impl Process {
    pub fn load() -> Self {
        serde_json::from_str(PROCESS_JSON).expect("process.json parses")
    }

    /// Build a per-step plan keyed in the SAME order as `step_ids`.
    pub fn plans(&self, step_ids: &[String]) -> Vec<StepPlan> {
        step_ids
            .iter()
            .map(|sid| {
                let mut ops: Vec<&Op> = self.ops.iter().filter(|o| &o.step == sid).collect();
                ops.sort_by_key(|o| o.seq);
                let total: f32 = ops
                    .iter()
                    .map(|o| o.dur_min.max(0.1))
                    .sum::<f32>()
                    .max(1e-3);
                let mut acc = 0.0_f32;
                let mut phase = Vec::new();
                let (mut bs, mut be) = (1.0_f32, 0.0_f32);
                for o in &ops {
                    let f0 = acc / total;
                    acc += o.dur_min.max(0.1);
                    let f1 = acc / total;
                    if is_build(&o.action) {
                        bs = bs.min(f0);
                        be = be.max(f1);
                    }
                    phase.push(PhaseOp {
                        op: (*o).clone(),
                        f0,
                        f1,
                    });
                }
                if bs > be {
                    bs = 0.0;
                    be = 1.0;
                }
                StepPlan {
                    ops: phase,
                    build_start: bs,
                    build_end: be,
                }
            })
            .collect()
    }
}

impl StepPlan {
    /// The op active at within-step fraction `p` (0..1).
    pub fn op_at(&self, p: f32) -> Option<&PhaseOp> {
        self.ops
            .iter()
            .find(|po| p >= po.f0 && p < po.f1)
            .or_else(|| self.ops.last())
    }

    /// Geometry build progress (0..1) for within-step fraction `p`: zero until
    /// the build window opens, then ramps to 1 across it.
    pub fn build_progress(&self, p: f32) -> f32 {
        let span = (self.build_end - self.build_start).max(1e-3);
        ((p - self.build_start) / span).clamp(0.0, 1.0)
    }

    /// True while a logistics op (搬入/搬送) is active — drives the delivery cart.
    pub fn logistics_at(&self, p: f32) -> Option<f32> {
        for po in &self.ops {
            if is_logistics(&po.op.action) && p >= po.f0 && p < po.f1 {
                let span = (po.f1 - po.f0).max(1e-3);
                return Some(((p - po.f0) / span).clamp(0.0, 1.0));
            }
        }
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn process_loads_and_plans() {
        let p = Process::load();
        assert!(p.ops.len() > 100, "ops={}", p.ops.len());
        // a representative step has the full procure→inspect chain
        let steel: Vec<&Op> = p.ops.iter().filter(|o| o.step == "step:05-steel").collect();
        let actions: Vec<&str> = steel.iter().map(|o| o.action.as_str()).collect();
        assert!(actions.contains(&"procure"));
        assert!(actions.contains(&"deliver"));
        assert!(actions.contains(&"weld"));
        assert!(actions.contains(&"inspect"));
    }

    #[test]
    fn plan_phases_are_ordered() {
        let p = Process::load();
        let ids = vec!["step:05-steel".to_string()];
        let plan = &p.plans(&ids)[0];
        assert!(plan.build_start < plan.build_end);
        // procure is before the build window; inspect is after
        assert!(plan.op_at(0.01).unwrap().op.action == "procure");
        assert!(plan.build_progress(0.0) < 0.01);
        assert!(plan.build_progress(1.0) > 0.99);
        assert!(plan.logistics_at(0.0).is_none()); // procure first, not logistics
    }
}
