;; author.clj — Ghost Hacker: Shiro & Pico / isekai-network, scene authoring.
;;
;; Faithful reskin of kami-clj-play/games/survivors/author.clj (ADR-0036): clj
;; is the brain, datalevin (Datalog) owns the scene data, the Rust/wgpu player
;; is the GPU arm. This script TRANSACTS the per-tag render profiles + world
;; tuning as datoms, reads them back with a Datalog QUERY, and PROJECTS that to
;; `scene.edn` — the snapshot the Rust host consumes.
;;
;;   clojure -M author.clj
;;
;; Re-run after changing the data below; the player picks up the new scene.edn.
;; Colours are taken from the canonical palette in
;; orgs/gftdcojp/ai-gftd-mangaka/data/ghosthacker-shiropico/character-design-spec.json
;; (shiro teal #1FB6A6, ghost body #29D3C2, ghost "heat afterimage" #F4F8F7).

(require '[datalevin.core :as d]
         '[clojure.pprint :as pp]
         '[clojure.java.io :as io])

;; ── schema (the Datalog vocabulary for a renderable game entity) ────────────
(def schema
  {:profile/tag   {:db/valueType :db.type/string  :db/unique :db.unique/identity}
   :profile/r     {:db/valueType :db.type/double}
   :profile/g     {:db/valueType :db.type/double}
   :profile/b     {:db/valueType :db.type/double}
   :profile/size  {:db/valueType :db.type/double}
   :profile/glow  {:db/valueType :db.type/double}
   :profile/pulse {:db/valueType :db.type/boolean}})

;; ── the authored scene data ──────────────────────────────────────────────
;; "shiro-pico" = the duo moves as one controllable unit in this mode (concept
;; 1/5, design/01-netsurvivors.edn). "ghost" = the only bestiary member wired
;; up in this first prototype slice; daemon/zombie are design/00-game-bible.edn
;; future work, not yet in logic.clj.
(def profiles
  [{:profile/tag "shiro-pico" :profile/r 0.12 :profile/g 0.71 :profile/b 0.65 :profile/size 0.045 :profile/glow 0.80 :profile/pulse true}
   {:profile/tag "ghost"      :profile/r 0.16 :profile/g 0.83 :profile/b 0.76 :profile/size 0.030 :profile/glow 0.40 :profile/pulse false}])

;; world tuning + fx live alongside the profiles (small global config).
;; Values kept identical to kami-clj-play/games/survivors on purpose — this
;; slice is a rename + recolour, not a rebalance.
(def world {:player-speed 240.0 :camera-scale 620.0 :arena 460.0})
(def background {:top [0.06 0.07 0.12] :bottom [0.05 0.11 0.13] :grid 80.0})
;; burst = the "purify" effect on defeat: a soft white heat afterimage
;; (ghost's canonical #F4F8F7), not a violent explosion — matches
;; "倒す ≠ 殺す" / 7+ rating guardrail from design/00-game-bible.edn.
(def burst {:count 10 :speed 150.0 :life 0.6 :color [0.96 0.97 0.97] :size 0.014})

(def db-dir (str (System/getProperty "user.dir") "/.datalevin"))

(defn -main []
  ;; fresh store each run so the snapshot is reproducible
  (let [conn (d/get-conn db-dir schema)]
    (d/clear conn)
    (let [conn (d/get-conn db-dir schema)]
      (d/transact! conn profiles)

      ;; Datalog query: pull every render profile back out of the DB.
      (let [rows (d/q '[:find ?tag ?r ?g ?b ?size ?glow ?pulse
                        :where
                        [?e :profile/tag ?tag]
                        [?e :profile/r ?r] [?e :profile/g ?g] [?e :profile/b ?b]
                        [?e :profile/size ?size] [?e :profile/glow ?glow]
                        [?e :profile/pulse ?pulse]]
                      (d/db conn))
            ;; project rows → the scene.edn :render/profiles shape
            prof-map (into (sorted-map)
                           (for [[tag r g b size glow pulse] rows]
                             [(keyword tag)
                              (cond-> {:color [r g b] :size size :glow glow}
                                pulse (assoc :pulse true))]))
            scene {:game/id           :gftd.games/isekai-network
                   :game/title        "Ghost Hacker: Shiro & Pico — Isekai Network"
                   :world             world
                   :render/profiles   prof-map
                   :render/background background
                   :fx/burst          burst}
            header (str ";; GENERATED by author.clj — datalevin (Datalog) is the source of truth.\n"
                        ";; Edit author.clj data + re-run `clojure -M author.clj`; do not hand-edit.\n"
                        ";; ADR-0036: datoms → Datalog query → scene snapshot the Rust GPU arm reads.\n\n")]
        (spit "scene.edn" (str header (with-out-str (pp/pprint scene))))
        (d/close conn)
        (println (str "author: transacted " (count profiles)
                      " profiles into datalevin, queried " (count rows)
                      " back, wrote scene.edn"))))))

(-main)
