//! kami-render: wgpu-unified renderer + camera + mesh + pipeline.
//!
//! Single backend (wgpu) covers all platforms. Shannon: 1 renderer, 0 redundancy.

pub mod asset;
pub mod camera;
pub mod logo;
pub mod mesh;
pub mod splat;
pub mod splat_loader;
pub mod texture;

#[cfg(feature = "gltf-loader")]
pub mod gltf_loader;

#[cfg(feature = "gltf-loader")]
pub mod meshopt;

#[cfg(feature = "gltf-loader")]
pub mod basisu;

#[cfg(feature = "gltf-loader")]
pub(crate) mod uastc_tables;

#[cfg(feature = "wgpu-backend")]
pub mod pipeline;

#[cfg(feature = "wgpu-backend")]
pub mod bootstrap;

#[cfg(feature = "wgpu-backend")]
pub mod wgpu_renderer;

/// EDN-generated native pipeline specs (cull / depth / blend) — one source with the web side
/// (kami.pipelines). Generated by `bb gen-pipeline-specs`; the parity gate holds it == scene_pipelines.
pub mod pipeline_specs;
#[cfg(feature = "wgpu-backend")]
pub mod scene_pipelines;

#[cfg(feature = "wgpu-backend")]
pub mod raytrace;

#[cfg(feature = "gaussian-splat")]
pub mod splat_pipeline;

#[cfg(feature = "wgpu-backend")]
pub use bootstrap::{Backend, BootstrapError, RenderContext};

#[cfg(all(feature = "wgpu-backend", not(target_family = "wasm")))]
pub use bootstrap::OffscreenContext;

#[cfg(feature = "wgpu-backend")]
pub use wgpu_renderer::WgpuRenderer;

pub use camera::{Camera, CameraUniform, LightUniform, MaterialUniform};

use kami_core::ipc::Column;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct MeshHandle(pub u32);

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct MaterialHandle(pub u32);

/// Draw command: which mesh, which material, what transform.
pub struct DrawCmd {
    pub mesh: MeshHandle,
    pub material: MaterialHandle,
    pub transform: glam::Mat4,
}

pub trait Renderer {
    /// Upload mesh from KAMI Columns (legacy path).
    unsafe fn upload_mesh(
        &mut self,
        positions: &Column,
        normals: &Column,
        uvs: &Column,
        indices: &Column,
    ) -> MeshHandle;

    /// Upload pre-interleaved mesh data (32B/vertex: pos3+norm3+uv2).
    fn upload_mesh_interleaved(&mut self, vertices: &[f32], indices: &[u32]) -> MeshHandle;

    unsafe fn update_vertex_buffer(&mut self, mesh: MeshHandle, positions: &Column);

    /// Create a material with PBR parameters and return its handle.
    fn create_material(&mut self, uniform: MaterialUniform) -> MaterialHandle;

    fn draw(&mut self, camera: &camera::Camera, commands: &[DrawCmd]);

    fn present(&mut self);

    fn resize(&mut self, width: u32, height: u32);
}
