;; author.clj — KAMI Survivors scene authoring, datalevin as the source of truth.
;;
;; ADR-0036: clj is the brain, datalevin (Datalog) owns the scene data, and the
;; Rust/wgpu player is the GPU arm. This script TRANSACTS the per-tag render
;; profiles + world tuning as datoms, reads them back with a Datalog QUERY, and
;; PROJECTS that to `scene.edn` — the snapshot the Rust host consumes. Editing
;; the game's look is now a transaction, not a hand-edited file.
;;
;;   clojure -M author.clj
;;
;; Re-run after changing the data below; the player picks up the new scene.edn.

(require '[datalevin.core :as d]
         '[clojure.pprint :as pp]
         '[clojure.java.io :as io])

;; ── schema (the Datalog vocabulary for a renderable game entity) ────────────
(def schema
  {:profile/tag   {:db/valueType :db.type/string  :db/unique :db.unique/identity}
   :profile/r     {:db/valueType :db.type/double}
   :profile/g     {:db/valueType :db.type/double}
   :profile/b     {:db/valueType :db.type/double}
   :profile/size  {:db/valueType :db.type/double}
   :profile/glow  {:db/valueType :db.type/double}
   :profile/pulse {:db/valueType :db.type/boolean}})

;; ── the authored scene data (this is what a designer edits / a tool transacts) ──
(def profiles
  [{:profile/tag "player" :profile/r 0.45 :profile/g 0.78 :profile/b 1.0  :profile/size 0.045 :profile/glow 0.70 :profile/pulse true}
   {:profile/tag "enemy"  :profile/r 1.0  :profile/g 0.33 :profile/b 0.36 :profile/size 0.030 :profile/glow 0.45 :profile/pulse false}])

;; world tuning + fx live alongside the profiles (small global config).
(def world {:player-speed 240.0 :camera-scale 620.0 :arena 460.0})
(def background {:top [0.06 0.07 0.12] :bottom [0.16 0.10 0.20] :grid 80.0})
(def burst {:count 10 :speed 180.0 :life 0.5 :color [1.0 0.55 0.15] :size 0.012})

(def db-dir (str (System/getProperty "user.dir") "/.datalevin"))

(defn -main []
  ;; fresh store each run so the snapshot is reproducible
  (let [conn (d/get-conn db-dir schema)]
    (d/clear conn)
    (let [conn (d/get-conn db-dir schema)]
      (d/transact! conn profiles)

      ;; Datalog query: pull every render profile back out of the DB.
      (let [rows (d/q '[:find ?tag ?r ?g ?b ?size ?glow ?pulse
                        :where
                        [?e :profile/tag ?tag]
                        [?e :profile/r ?r] [?e :profile/g ?g] [?e :profile/b ?b]
                        [?e :profile/size ?size] [?e :profile/glow ?glow]
                        [?e :profile/pulse ?pulse]]
                      (d/db conn))
            ;; project rows → the scene.edn :render/profiles shape
            prof-map (into (sorted-map)
                           (for [[tag r g b size glow pulse] rows]
                             [(keyword tag)
                              (cond-> {:color [r g b] :size size :glow glow}
                                pulse (assoc :pulse true))]))
            scene {:game/id           :gftd.games/survivors
                   :game/title        "KAMI Survivors"
                   :world             world
                   :render/profiles   prof-map
                   :render/background background
                   :fx/burst          burst}
            header (str ";; GENERATED by author.clj — datalevin (Datalog) is the source of truth.\n"
                        ";; Edit author.clj data + re-run `clojure -M author.clj`; do not hand-edit.\n"
                        ";; ADR-0036: datoms → Datalog query → scene snapshot the Rust GPU arm reads.\n\n")]
        (spit "scene.edn" (str header (with-out-str (pp/pprint scene))))
        (d/close conn)
        (println (str "author: transacted " (count profiles)
                      " profiles into datalevin, queried " (count rows)
                      " back, wrote scene.edn"))))))

(-main)
